### PR TITLE
test: Add new user login UI test

### PR DESCRIPTION
**Pull request by connected-mhuang**
We add new user login UI test. During this test, we make use of restmail as our fake email address to register fxa account. After everything is done, we remove the account from both restmail and fxa. At the same time, we remove the city verification from connection test and update the timeout for all sessions. In the meantime, we update setting UI test since the UI updated recently.

### CODE REVIEW

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://635-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://640-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://642-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://651-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://654-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Comment by connected-cmo** [comment]
@connected-mhuang Do these tests create fake accounts using restmail against the production FxA endpoint (and if so, have we confirmed that this is something that is ok to do)?  If there are any interruptions to the test, how do are we ensuring that the FxA and restmail accounts get removed.

**Comment by connected-mhuang** [comment]
> @connected-mhuang Do these tests create fake accounts using restmail against the production FxA endpoint (and if so, have we confirmed that this is something that is ok to do)? If there are any interruptions to the test, how do are we ensuring that the FxA and restmail accounts get removed.

It is against staging env. I already talked with @rlr regarding the account creation issues. We both agree to use restmail as fake email and then UI test will eventually remove the account from staging env after test finish.  We remove the account from FxA by clicking delete button on Manage Account page. We remove the restmail by calling its DELETE account API which is public anyway.

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://676-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Comment by mhuang-connectedqa** [comment]
<h3>Errors: 0, Warnings: 0</h3>
    Details: <strong><a href='https://689-220557697-gh.circle-artifacts.com/0/test/result/Output.log' target='_blank'>details</a></strong>

**Pull request merged**
